<?php
// on customise le formulaire pour l'affichage
$form = $this->form;
$auth = $form->get('login');
$auth->setAttribute( 'class', 'form-control');
$auth->setAttribute('placeholder', 'Login');
$pwd = $form->get('pwd');
$pwd->setAttribute( 'class', 'form-control');
$pwd->setAttribute('placeholder', 'Password');
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success btn-xs');

$form->setAttributes( array(
    'action' => $this->url('default', array('action' => 'form' )),
    'class' => 'navbar-form navbar-right',
    )
);

$form->prepare();

// on affiche
echo '<li>';
echo $this->form()->openTag($form);
echo '<div class="form-group">';
echo $this->formRow($form->get('login'));
echo '</div>&nbsp;';
echo '<div class="form-group">';
echo $this->formRow($form->get('pwd'));
echo '</div>&nbsp;';
echo $this->formButton()->render( $submit, 'Se Connecter' );
echo $this->form()->closeTag();
echo '</li>';


$this->inlineScript()->captureStart();
echo <<<JS

var traiteSubmit = function() {
    $.ajax({
        url: '{$this->url('default', array('action' => 'inscription' ))}',
        method: 'POST',
        dataType: 'html',
        data: $(this).serialize(),
        statusCode: {
            205: function(data, xhr, request) {
                alert('Inscription validée');
                var url = request.getResponseHeader('Location');
                window.location.href = url;
            },
            200: function(dataRecu) {
                $('.modal-content').replaceWith(dataRecu);
                $('#{$this->newUserForm->getAttribute('id')}').on('submit', traiteSubmit )
            }
        }
    });
    return false;
};

$(document).ready( function() {
    $('#{$this->newUserForm->getAttribute('id')}').on('submit', traiteSubmit );
});
JS;
$this->inlineScript()->captureEnd();
?>
<li>
    &nbsp;<button type="button" class="btn btn-primary btn-xs navbar-btn" data-toggle="modal" data-target="#inscriptionModal">S'inscrire</span></button>
</li>

<?php
$form = $this->newUserForm;
$form->prepare();
?>
<!-- Modal -->
<div class="modal fade" id="inscriptionModal" tabindex="-1" role="dialog" aria-labelledby="inscriptionModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <?php echo $this->form()->openTag($form); ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="inscriptionModalLabel">Créez votre compte</h4>
            </div>
            <div class="modal-body">
                Votre login : <?php echo $this->formText( $form->get('login') ); ?><br/>
                Votre password : <?php echo $this->formPassword( $form->get('pwd') ); ?><br/>
                <?php echo $this->formCaptcha( $form->get('newUserCaptcha')); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">s'inscrire</button>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>